export { default as Favicon } from "/public/images/favicon.ico"
export { default as LogoImage } from "/public/images/logo.png"

export { default as SocialYelp } from "/public/images/social-yelp.svg"
export { default as SocialGoogleStore } from "/public/images/social-google-store.svg"
export { default as SocialLinkedin } from "/public/images/social-linkedin.svg"
export { default as SocialInstagram } from "/public/images/social-instagram.svg"
export { default as SocialFacebook } from "/public/images/social-facebook.svg"

export { default as PhotoMainSlide } from "/public/images/h1-slider-2a-background-img.jpg"
export { default as PhotoStreamBox } from "/public/images/h1-streambox-v2-img-1.jpg"
export { default as PhotoGallery01 } from "/public/images/h1-gallery-img-6.jpg"
export { default as PhotoSpeciality } from "/public/images/port-2-img-12.jpg"
export { default as PhotoBlog01 } from "/public/images/blog-2-img-1.jpg"
export { default as PhotoBlog02 } from "/public/images/blog-2-img-2.jpg"
export { default as PhotoBlog03 } from "/public/images/blog-2-img-3.jpg"
export { default as PhotoVS } from "/public/images/vs_dark.png"
export { default as PhotoTeam01 } from "/public/images/team1-banner.png"
export { default as PhotoTeam02 } from "/public/images/team2-banner.png"
export { default as PhotoTeam03 } from "/public/images/team3-banner.png"
export { default as PhotoTeam04 } from "/public/images/team4-banner.png"
export { default as PhotoTeam05 } from "/public/images/team5-banner.png"
export { default as PhotoTeam06 } from "/public/images/team6-banner.png"
export { default as PhotoTeam07 } from "/public/images/team7-banner.png"
export { default as PhotoAbout } from "/public/images/p2-slider-background-img-1.jpg"
export { default as PhotoAboutMe } from "/public/images/p1-img-1.jpg"

export { default as PhotoUser_01 } from "/public/images/users/01.jpg"
export { default as PhotoUser_02 } from "/public/images/users/02.jpg"
export { default as PhotoUser_03 } from "/public/images/users/03.jpg"
export { default as PhotoUser_04 } from "/public/images/users/04.jpg"
export { default as PhotoUser_05 } from "/public/images/users/05.jpg"
export { default as PhotoUser_06 } from "/public/images/users/06.jpg"
export { default as PhotoUser_07 } from "/public/images/users/07.jpg"
export { default as PhotoUser_08 } from "/public/images/users/08.jpg"
export { default as PhotoUser_09 } from "/public/images/users/09.jpg"
export { default as PhotoUser_10 } from "/public/images/users/10.jpg"

export { default as IconTick } from "/public/images/tick.svg"
export { default as IconCalendar } from "/public/images/icon-calendar.svg"
export { default as IconSearch } from "/public/images/icon-search.svg"
export { default as IconBell } from "/public/images/icon-bell.svg"
export { default as IconEdit } from "/public/images/icon-edit.svg"
export { default as IconTrash } from "/public/images/icon-trash.svg"
export { default as IconAttach } from "/public/images/icon-attach.svg"
export { default as IconEnvelope } from "/public/images/icon-envelope.svg"
export { default as IconHeart } from "/public/images/icon-heart.svg"
export { default as IconDownloadCsv } from "/public/images/download_csv_icon.svg"
export { default as IconSend } from "/public/images/send_icon.svg"
export { default as IconMap } from "/public/images/icon-map.svg"
export { default as IconList } from "/public/images/icon-list.svg"

export { default as VectorPaypal } from "/public/images/paypal.svg"
export { default as VectorVisa } from "/public/images/visa.svg"
export { default as VectorBank } from "/public/images/bank.svg"
